### ISSUE TITLE
Migrate to washer.thu.services as a better algorithm was implmented

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [Konano/Tuna-BetaCat-Bot#6]
Ref to https://github.com/ZenithalHourlyRate/thuservices/pull/12, a better algorithm was implemented.

You may refer to the document https://github.com/ZenithalHourlyRate/thuservices/blob/master/docs/utils.md#%E5%85%A8%E6%A0%A1%E6%B4%97%E8%A1%A3%E6%9C%BA%E7%8A%B6%E6%80%81

**Comment by Konano** [comment]
The query takes too long. It often takes more than a second.

**Comment by ZenithalHourlyRate** [comment]
The current implementation does not parallelly fetch all the results. I will implement this feature soon.

**Comment by ZenithalHourlyRate** [comment]
> The current implementation does not parallelly fetch all the results. I will implement this feature soon.

Implemented.
